{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "polling.database" . }}"
  labels:
{{ include "polling.labels" . | indent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ template "polling.database.encryptedPassword" . }}
{{- end -}}
