apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-cron
  labels:
    name: zipkin-cron
  namespace: zipkin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zipkin-cron
    spec:
      containers:
      - name: zipkin-cron
        image: openzipkin/zipkin-dependencies:1.4.0
        env:
        - name: STORAGE_TYPE
          value: mysql
        - name: MYSQL_HOST
          value: zipkin-mysql
        - name: MYSQL_USER
          value: zipkin
        - name: MYSQL_PASS
          value: zipkin
        command: ["crond"]
        args: ["-f"]
      nodeSelector:
        beta.kubernetes.io/os: linux