---
- hosts: all
  tasks:
  - name: the first task
    file:
      dest: $HOME/tmp/first-task
      state: '{{file_state}}'
  - name: the second task
    file:
      dest: $HOME/tmp/second-task
      state: '{{file_state}}'
  - name: the last task
    file:
      dest: $HOME/tmp/last-task
      state: '{{file_state}}'
