---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: user-db
  labels:
    name: user-db
  namespace: sock-shop
spec:
  selector:
    matchLabels:
      app: user-db
  serviceName: user-db
  replicas: 1
  template:
    metadata:
      labels:
        name: user-db
        app: user-db
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: user-db
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /data/db-users
          name: user-db-vol
      
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
  volumeClaimTemplates:
  - metadata:
      name: user-db-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
