apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: logging-workflow-
spec:
  entrypoint: sock-shop-logging

  templates:
  - name: sock-shop-logging
    steps:
    - - name: logging-deploy
        template: kubectl-create
        arguments:
          parameters:
          - name: repo-manifest-dir
            value: "example-cd/logging"

    - - name: kibana-up
        template: check-lb-service-up
        arguments:
          parameters:
          - name: service-name
            value: kibana
          - name: service-namespace
            value: kube-system
          - name: lb-check-timeout
            value: 300
          - name: lb-check-period
            value: 5
        
  - name: kubectl-create
    inputs:
      parameters:
      - name: repo-manifest-dir
      artifacts:
      - name: git-artifact
        path: /src
        git:
          repo: "https://github.com/argoproj/example-cd.git"
          revision: "master"
    container:
      image: docker.io/argoproj/kubectl:sh-v1.8.3
      command: ["/bin/sh", "-c"]
      args: ["kubectl create -f /src/{{inputs.parameters.repo-manifest-dir}} --validate=false"]
      # args: ["kubectl create -f {{inputs.parameters.repo-manifest-dir}}"]
      imagePullPolicy: Always

  - name: check-lb-service-up
    inputs:
      parameters:
      - name: service-name
      - name: service-namespace
      - name: lb-check-timeout
      - name: lb-check-period
    container:
      image: docker.io/argoproj/kubectl:sh-v1.8.3
      command: ["/bin/bash", "-x", "-c"]
      args: ["ITER=0; MAX_ITER=$(( {{inputs.parameters.lb-check-timeout}} / {{inputs.parameters.lb-check-period}} )); while [ ${ITER} -lt ${MAX_ITER} ]; do IP=$(kubectl get service {{inputs.parameters.service-name}} --namespace {{inputs.parameters.service-namespace}} -o json | jq '.status.loadBalancer.ingress[0].ip'); if [ \"${IP}\" != \"null\" ]; then echo \"{{inputs.parameters.service-name}} load balanced service came up on ip ${IP}\"; exit 0; fi; echo \"Waiting for service to come up\"; sleep {{inputs.parameters.lb-check-period}}; ITER=$((ITER+1)); done; echo \"ERROR: Timeout waiting for service to come up\"; exit 1"]
      imagePullPolicy: Always
