apiVersion: v1
kind: Service
metadata:
  name: "{{ template "polling.api" . }}"
  labels:
{{ include "polling.labels" . | indent 4 }}
    component: api
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "polling.matchLabels" . | indent 4 }}
    component: api

