Vagrant.require_version ">= 1.7.0"

$os_image = (ENV['OS_IMAGE'] || "centos7").to_sym

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"

  def set_vbox(vb, config)
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 2

    case $os_image
    when :centos7
      config.vm.box = "centos/7"
    when :ubuntu16
      config.vm.box = "bento/ubuntu-16.04"
    end
  end

  ips = ["192.168.33.57", "192.168.33.62"]
  (0..1).each do |id|
    mid = id + 1
    config.vm.define "k8s-node#{mid}" do |node|
      node.vm.hostname = "k8s-node#{mid}"
      node.vm.network :private_network, ip: "#{ips[id]}",  auto_config: true
      node.vm.provider :virtualbox do |vb, override|
        vb.name = "k8s-node#{mid}"
        set_vbox(vb, override)
      end
    end
  end
end